import Link from "next/link";
import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";
import RefreshButton from "@/pages/api/RefreshBtn";
import Image from "next/image";

const inter = Noto_Sans_KR({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  const cookieStore = cookies();
  let res = cookieStore.get("mode");

  return (
    <html lang="en" className={inter.className}>
      <body
        className={res != undefined && res.value == "dark" ? "dark-mode" : ""}
      >
        <div className="navbar">
          <div
            style={{
              display: "flex",
              alignItems: "center",
              flexWrap: "wrap",
              justifyContent: "space-between",
            }}
          >
            <div>
              <div>
                <Link href="/list">List</Link>
                <Link href="/photos">Photos</Link>
              </div>

              <div>
                <Link href="/write">Post</Link>
                <Link href="/upload">Upload</Link>
              </div>
            </div>

            <div>
              <Link href="/">
                {res.value == "dark" ? (
                  <Image
                    src="/whiteLogo.png"
                    width={100}
                    height={100}
                    alt="home"
                  />
                ) : (
                  <Image
                    src="/blackLogo.png"
                    width={100}
                    height={100}
                    alt="home"
                  />
                )}
              </Link>
            </div>
            <div>
              <div style={{ display: "flex" }}>
                {session != null ? (
                  <div>
                    <span style={{ marginRight: "10px" }}>
                      {session.user.name}
                    </span>
                    <LogoutBtn />
                  </div>
                ) : (
                  <LoginBtn />
                )}
              </div>
              <div style={{ display: "flex", flexDirection: "row-reverse" }}>
                <RefreshButton />
                <DarkMode current={res.value} />
              </div>
            </div>
          </div>
        </div>
        {children}

        <div style={{ padding: "10px" }}>
          <p style={{ textAlign: "center", margin: 0 }}>Made by Sunny Kim</p>
        </div>
      </body>
    </html>
  );
}
