import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";
import RefreshButton from "@/pages/api/RefreshBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  const cookieStore = cookies();
  let res = cookieStore.get("mode");

  return (
    <html lang="en">
      <body
        className={res != undefined && res.value == "dark" ? "dark-mode" : ""}
      >
        <div className="navbar">
          <div
            style={{
              display: "flex",
              alignItems: "baseline",
              flexWrap: "wrap",
              justifyContent: "space-between",
            }}
          >
            <div>
              <Link href="/" className="logo">
                Appleforum
              </Link>
              <Link href="/list">List</Link>
              <Link href="/photos">Photos</Link>
              <RefreshButton />
              <div>
                <Link href="/upload">Upload</Link>
                <Link href="/write">Post</Link>
              </div>
            </div>
            <div>
              <DarkMode current={res.value} />
              {session != null ? (
                <span>
                  {session.user.name}
                  <LogoutBtn />
                </span>
              ) : (
                <LoginBtn />
              )}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
